apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: beverage_data
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true