apiVersion: 1

datasources:
  - name: TimescaleDB
    type: grafana-postgresql-datasource
    uid: ef38fe8vzbrpcf
    orgId: 1
    access: proxy
    url: timescaledb:5432
    database: beverage_data
    user: admin
    isDefault: true
    editable: false
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true

  - name: Redis
    type: redis-datasource
    uid: redis-datasource
    orgId: 1
    access: proxy
    url: redis:6379
    isDefault: false
    editable: false
    jsonData:
      client: standalone
      tlsSkipVerify: true